[project]
name = "otaku-manga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "humanize>=4.13.0",
    "markdown>=3.8.2",
    "pyyaml>=6.0.2",
]
